version: "3.9"

services:
  web:
    build: .
    command: python -m aiohttp.web -H $HOSTNAME -P $PORT main:create_app
    volumes:
      - .:/code
    restart: unless-stopped
    env_file:
      - .env
    network_mode: "host"