services:
  web:
    build: .
    command: python -m aiohttp.web -H $HOSTNAME -P $PORT main:create_app
    volumes:
      - .:/code
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - 8081:8080
    healthcheck:
      test: curl -sS http://127.0.0.1:8080/healthz || exit 1
      timeout: 3s
